### ISSUE TITLE
mime-types should be dependency (not devDependency)

### ISSUE THREAD

**Issue by canadaduane** [automerge/hypermerge#17]
When including hypermerge master as a dependency of another project, hypermerge fails with the following error message:

```
Error: Cannot find module 'mime-types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dujohnson/medici/local-first/delta-agent/node_modules/hypermerge/dist/RepoFrontend.js:22:38)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

I think `mime-types` needs to be moved to `dependencies` rather than `devDependencies`.

**Comment by pvh** [comment]
Fixed, thanks.

**Comment by pvh** [comment]
(Also fixed in pushpin which had the same problem.)
